[profile.default]
solc_version = "0.8.30"
src = "solidity"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# https://github.com/argotorg/solidity/releases/download/v<version>/solc-static-linux
